@url = http://localhost:8081
@url_keycloak = http://localhost:8080


###
# @name campaign_create
POST {{url}}/api/v1/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "Campaign 1",
    "content": "Content 1",
    "emails": [
        "mmmsieto@hotmail.com", "mmmsieto@gmail.com"
    ]
}

###
@campaign_id = {{campaign_create.response.body.id}}

###

GET {{url}}/api/v1/ping

###

GET {{url}}/api/v1/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

PATCH  {{url}}/api/v1/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

PATCH   {{url}}/api/v1/campaigns/start/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

DELETE   {{url}}/api/v1/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
# @name token
POST {{url_keycloak}}/realms/provider/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=emailIn
&username=mmmsieto@hotmail.com
&password=123456
&grant_type=password

###

@access_token = {{token.response.body.access_token}}

