@url = http://localhost:8081
@url_keycloak = http://localhost:8080
###

POST {{url}}/api/v1/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "Campaign 1",
    "content": "Content 1",
    "emails": [
        "tests@gmail.com"
    ]
}

###

GET {{url}}/api/v1/ping

###

GET {{url}}/api/v1/campaigns
Authorization: Bearer {{access_token}}

###

GET {{url}}/api/v1/campaigns/cl7c8l7u0bqirj6oth40
Authorization: Bearer {{access_token}}

###

PATCH  {{url}}/api/v1/campaigns/cl3sl5vu0bqo7tpeqk8g
Authorization: Bearer {{access_token}}

###

DELETE   {{url}}/api/v1/campaigns/cl3vdkvu0bqrt45m9r10
Authorization: Bearer {{access_token}}

###
# @name token
POST {{url_keycloak}}/realms/provider/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=emailIn
&username=mmmsieto@hotmail.com
&password=123456
&grant_type=password

###

@access_token = {{token.response.body.access_token}}
